name: Update Formula on New Release
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  update-formula:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout tap repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          
      - name: Set up environment
        run: |
          echo "FORMULA_PATH=bailiff.rb" >> $GITHUB_ENV
      
      - name: Fetch latest release info
        run: |
          RELEASE_DATA=$(curl -s https://api.github.com/repos/livetheoogway/bailiff/releases/latest)
          TAG_NAME=$(echo "$RELEASE_DATA" | jq -r .tag_name)
          
          if [ "$TAG_NAME" == "null" ]; then
            echo "No release found"
            exit 1
          fi
          
          VERSION=${TAG_NAME#v}
          TARBALL_URL="https://github.com/livetheoogway/bailiff/archive/refs/tags/$TAG_NAME.tar.gz"
          
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "TARBALL_URL=$TARBALL_URL" >> $GITHUB_ENV
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
      
      - name: Calculate SHA256
        run: |
          # Create a temporary directory
          TEMP_DIR=$(mktemp -d)
          curl -sL "$TARBALL_URL" -o "$TEMP_DIR/release.tar.gz"
          SHA256=$(sha256sum "$TEMP_DIR/release.tar.gz" | cut -d' ' -f1)
          # Delete the tarball after calculating the hash
          rm -f "$TEMP_DIR/release.tar.gz"
          rmdir "$TEMP_DIR"
          echo "SHA256=$SHA256" >> $GITHUB_ENV
      
      - name: Check current formula version
        run: |
          # Extract version from URL and clean it
          URL_VERSION=$(grep -o 'tags/v[0-9.]*' $FORMULA_PATH | cut -d'/' -f2 | tr -d 'v' | sed 's/.$//' || echo "none")
          # If that didn't work, try again with a different approach
          if [ "$URL_VERSION" = "none" ] || [ -z "$URL_VERSION" ]; then
            URL_VERSION=$(grep -o 'tags/v[0-9.]*' $FORMULA_PATH | sed 's/tags\/v\([0-9.]*\)/\1/' || echo "none")
          fi
          
          # Also check for version in test section as fallback
          TEST_VERSION=$(grep -o 'bailiff v[0-9.]*' $FORMULA_PATH | cut -d' ' -f2 | tr -d 'v' || echo "none")
          
          # Clean up any trailing periods that shouldn't be there
          URL_VERSION=$(echo "$URL_VERSION" | sed 's/\.$//')
          TEST_VERSION=$(echo "$TEST_VERSION" | sed 's/\.$//')
          
          # Use URL version or test version, whichever is valid
          if [ "$URL_VERSION" != "none" ] && [ ! -z "$URL_VERSION" ]; then
            CURRENT_VERSION="$URL_VERSION"
          elif [ "$TEST_VERSION" != "none" ] && [ ! -z "$TEST_VERSION" ]; then
            CURRENT_VERSION="$TEST_VERSION"
          else
            CURRENT_VERSION="none"
          fi
          
          echo "Detected version: $CURRENT_VERSION"
          
          CURRENT_SHA=$(grep -o 'sha256 "[^"]*"' $FORMULA_PATH | cut -d'"' -f2 || echo "none")
          
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
          echo "CURRENT_SHA=$CURRENT_SHA" >> $GITHUB_ENV
          
          if [ "$CURRENT_VERSION" == "$VERSION" ] && [ "$CURRENT_SHA" == "$SHA256" ]; then
            echo "Formula is already up to date"
            echo "NEEDS_UPDATE=false" >> $GITHUB_ENV
          else
            echo "Formula needs updating"
            echo "NEEDS_UPDATE=true" >> $GITHUB_ENV
          fi
      
      - name: Update formula
        if: env.NEEDS_UPDATE == 'true'
        run: |
          sed -i "s|url \".*\"|url \"$TARBALL_URL\"|" $FORMULA_PATH
          sed -i "s|sha256 \".*\"|sha256 \"$SHA256\"|" $FORMULA_PATH
          sed -i "s|version \".*\"|version \"$VERSION\"|" $FORMULA_PATH
          sed -i "s|\"bailiff v[0-9.]*\"|\"bailiff v$VERSION\"|" $FORMULA_PATH
      
      - name: Create Pull Request
        if: env.NEEDS_UPDATE == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          commit-message: "Update bailiff to ${{ env.VERSION }}"
          title: "Update bailiff to ${{ env.VERSION }}"
          body: |
            Updates bailiff formula to version ${{ env.VERSION }}
            
            Changes:
            - Updated URL to: ${{ env.TARBALL_URL }}
            - Updated SHA256 to: ${{ env.SHA256 }}
          branch: "update-bailiff-${{ env.VERSION }}"
          delete-branch: true




          